services:
  postgres:
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - APP_ENV
      - AUTH_SECRET
      - DATABASE_URL
      - EMAIL_ADDRESS
      - EMAIL_PASSWORD
      - EMAIL_PROVIDER
      - EMAIL_PROVIDER_API_KEY

volumes:
  postgres-data: